<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3Ae2SBJ\Shopware_Core_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3Ae2SBJ/Shopware_Core_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3Ae2SBJ.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3Ae2SBJ\Shopware_Core_KernelDevDebugContainer::class, Shopware_Core_KernelDevDebugContainer::class, false);
}

return new \Container3Ae2SBJ\Shopware_Core_KernelDevDebugContainer([
    'container.build_hash' => '3Ae2SBJ',
    'container.build_id' => 'c34ab5c8',
    'container.build_time' => 1703872363,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3Ae2SBJ');
