<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3rtyvxO\Shopware_Core_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3rtyvxO/Shopware_Core_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3rtyvxO.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3rtyvxO\Shopware_Core_KernelDevDebugContainer::class, Shopware_Core_KernelDevDebugContainer::class, false);
}

return new \Container3rtyvxO\Shopware_Core_KernelDevDebugContainer([
    'container.build_hash' => '3rtyvxO',
    'container.build_id' => '909c606c',
    'container.build_time' => 1703873503,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3rtyvxO');
