<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerExzcuJ1\Shopware_Core_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerExzcuJ1/Shopware_Core_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerExzcuJ1.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerExzcuJ1\Shopware_Core_KernelDevDebugContainer::class, Shopware_Core_KernelDevDebugContainer::class, false);
}

return new \ContainerExzcuJ1\Shopware_Core_KernelDevDebugContainer([
    'container.build_hash' => 'ExzcuJ1',
    'container.build_id' => 'cc77e5f4',
    'container.build_time' => 1703932025,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerExzcuJ1');
