<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBoxcd2A\Shopware_Core_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBoxcd2A/Shopware_Core_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBoxcd2A.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBoxcd2A\Shopware_Core_KernelDevDebugContainer::class, Shopware_Core_KernelDevDebugContainer::class, false);
}

return new \ContainerBoxcd2A\Shopware_Core_KernelDevDebugContainer([
    'container.build_hash' => 'Boxcd2A',
    'container.build_id' => 'b3ccb4e8',
    'container.build_time' => 1703876531,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBoxcd2A');
